version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      python-packages:
        patterns:
          - '*'
    commit-message:
      prefix: ⬆
    labels:
      - 'upgrade'

  - package-ecosystem: 'uv'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      python-packages:
        patterns:
          - '*'
    commit-message:
      prefix: ⬆
    labels:
      - 'upgrade'

  - package-ecosystem: 'cargo'
    directory: 'rust/crates'
    schedule:
      interval: 'monthly'
    groups:
      cargo-packages:
        patterns:
          - '*'
    commit-message:
      prefix: ⬆
    labels:
      - 'upgrade'
