"""asynchronous ORM that uses pydantic models to represent database tables ✨"""

__version__ = "2.0.0"

from ormdantic.association import association_proxy, hybrid_property
from ormdantic.engine import runtime_capabilities
from ormdantic.errors import (
    ConfigurationError,
    DatabaseConnectionError,
    HydrationError,
    MigrationError,
    MismatchingBackReferenceError,
    MustUnionForeignKeyError,
    NativeExtensionError,
    OrmdanticError,
    QueryCompilationError,
    QueryExecutionError,
    ReflectionError,
    RelationshipLoadingError,
    SchemaError,
    TransactionError,
    TypeConversionError,
    UndefinedBackReferenceError,
)
from ormdantic.events import EventRegistry
from ormdantic.expressions import (
    QueryExpression,
    RelationExpression,
    assignment,
    avg,
    case,
    cast,
    column,
    count,
    cte,
    exists,
    group,
    literal,
    max,
    min,
    not_,
    not_exists,
    over,
    projection,
    raw_sql_safe,
    select_query,
    subquery,
    sum,
    tuple_,
    update_query,
)
from ormdantic.loaders import (
    joined,
    joinedload,
    lazy,
    lazyload,
    load,
    noload,
    selectin,
    selectinload,
)
from ormdantic.models import (
    DatabaseNamespace,
    DatabaseSequence,
    DatabaseView,
    TableCheck,
    TableColumn,
    TableExclusion,
    TableForeignKey,
    TableIndex,
    TableUnique,
)
from ormdantic.orm import Ormdantic
from ormdantic.table import Order, Table

__all__ = [
    "Ormdantic",
    "Table",
    "Order",
    "TableColumn",
    "TableExclusion",
    "DatabaseNamespace",
    "DatabaseSequence",
    "DatabaseView",
    "TableIndex",
    "TableCheck",
    "TableUnique",
    "TableForeignKey",
    "OrmdanticError",
    "ConfigurationError",
    "QueryCompilationError",
    "QueryExecutionError",
    "DatabaseConnectionError",
    "SchemaError",
    "MigrationError",
    "ReflectionError",
    "RelationshipLoadingError",
    "HydrationError",
    "TransactionError",
    "NativeExtensionError",
    "UndefinedBackReferenceError",
    "MismatchingBackReferenceError",
    "MustUnionForeignKeyError",
    "TypeConversionError",
    "EventRegistry",
    "QueryExpression",
    "RelationExpression",
    "column",
    "projection",
    "assignment",
    "select_query",
    "update_query",
    "case",
    "cast",
    "tuple_",
    "cte",
    "count",
    "sum",
    "avg",
    "min",
    "max",
    "exists",
    "not_exists",
    "not_",
    "group",
    "over",
    "subquery",
    "literal",
    "raw_sql_safe",
    "association_proxy",
    "hybrid_property",
    "joined",
    "joinedload",
    "selectin",
    "selectinload",
    "lazy",
    "lazyload",
    "noload",
    "load",
    "runtime_capabilities",
]
